### ISSUE TITLE
bug: Build fails in XCode 26

### ISSUE THREAD

**Issue by langalex** [riderx/capacitor-updater#614]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 7.4.3
  @capacitor/core: 7.4.3
  @capacitor/android: 7.4.3
  @capacitor/ios: 7.4.3

Installed Dependencies:

  @capacitor/cli: 7.4.3
  @capacitor/core: 7.4.3
  @capacitor/android: 7.4.3
  @capacitor/ios: 7.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### Plugin Version

```
●   OS: darwin Darwin Kernel Version 25.0.0: Mon Aug 25 21:17:51 PDT 2025; root:xnu-12377.1.9~3/RELEASE_ARM64_T6000
│
●   Node: v22.17.0
│
●   Installed Dependencies:
│
●     @capgo/cli: 7.17.0
│
●     @capgo/capacitor-native-biometric: 7.1.13
│
●     @capgo/capacitor-updater: 7.13.11
│
●     @capgo/inappbrowser: 7.16.14
│
◇  Latest Dependencies:
│
●     @capgo/cli: 7.17.0
│
●     @capgo/capacitor-native-biometric: 7.1.13
│
●     @capgo/capacitor-updater: 7.13.11
│
●     @capgo/inappbrowser: 7.16.18
│

```

### context(s)

```md
ManualModel: false
AutoMode: true
CapgoCloud: true
OnPremise: false
```

### Platform(s)

XCode/iOS 26

### Current Behavior

When building the app in XCode, I get the following errors:

```
Build input files cannot be found: '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/AES.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BigInt.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleInfo.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleStatus.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CapacitorUpdaterPlugin.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CapgoUpdater.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CryptoCipherV2.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayCondition.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUntilNext.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUpdateUtils.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/InternalUtils.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/Logger.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/RSA.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/ShakeMenu.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/UserDefaultsExtension.swift'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?
Build input files cannot be found: '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/UserDefaultsExtension.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/ShakeMenu.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/RSA.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/Logger.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/InternalUtils.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUpdateUtils.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUntilNext.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayCondition.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CryptoCipherV2.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CapgoUpdater.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/CapacitorUpdaterPlugin.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleStatus.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleInfo.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/BigInt.swift', '<project dir>/node_modules/@capgo/capacitor-updater/ios/Plugin/AES.swift'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?

The `node_modules/@capgo/capacitor-updater` directory has no `ios` directory, only `android`.

```

### Expected Behavior

The build should pass as it did with previous XCode versions.

### Other Technical Details

`npm --version` output: using yarn 1.22.22

`node --version` output: v22.17.0

`pod --version` output (iOS issues only): 1.16.2

**Comment by riderx** [comment]
I apologize for this; I migrated the plugin to the new iOS architecture and forgot to update the file path sent to npm.
It should be fixed.

**Comment by langalex** [comment]
I'm still getting:

```
Build input files cannot be found: 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/UserDefaultsExtension.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/ShakeMenu.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/RSA.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/Logger.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/InternalUtils.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUpdateUtils.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayUntilNext.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/DelayCondition.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/CryptoCipherV2.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/CapgoUpdater.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/CapacitorUpdaterPlugin.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleStatus.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/BundleInfo.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/BigInt.swift', 'project-dir/node_modules/@capgo/capacitor-updater/ios/Plugin/AES.swift'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?
```

This is with `@capgo/capacitor-updater` at `7.18.0` and XCode 26.
